GET http://localhost:3001/api/persons/5effe3b1b71f8930603333df
##############

DELETE http://localhost:3001/api/persons/1
####################

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name":"Timon X",
    "number": "24234234"
}